# Project Setup
general:
  githubApiUrl: 'https://api.github.com'
  githubServerUrl: 'https://github.com'
  gitSshKeyCredentialsId: '00b6f4fb-3786-43d4-9aba-53e7014f77cc'
  githubTokenCredentialsId: 'github-token-os'
  buildWithXMake: false

steps:
  updatePackageRefs:
    deps: []
  pushChangesToRepo:
    branch: 'new-version'
  pollBuilds:
    timeoutSeconds: 5
    pollIntervalSeconds: 5
    branch: 'new-version'
  buildDepProjects:
    projects: ['release-sb-proxy', 'release-sap-sm']
  XMakeBuild:
    buildWithXMake: false

  setupPipelineEnvironment:
    buildDiscarder:
      daysToKeep: -1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    configYmlFile: '.pipeline/config.yml'
    githubApiUrl: 'https://api.github.com'
    gitHttpsUrl: 'https://github.com/${githubOrg}/${githubRepo}.git'
    gitSshUrl: 'git@github.com:${githubOrg}/${githubRepo}.git'
    relatedLibraries:
    - 'piper-lib-os'
    storeGithubStatistics: false
